name: Test
on:
  push:
    branches:
      - 'master'
  pull_request: {}
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable --silent

      - name: Check types
        run: yarn run typecheck

      - name: Check lint
        run: yarn run eslint

      - name: Build
        run: yarn run build

      - name: Jest run
        run: yarn run test

      - name: Report Fiber size
        run: yarn run analyze-fiber

      - name: Report Test Renderer size
        run: yarn run analyze-test

      - name: Check formatting
        run: yarn run format
