name: Test
on:
  push:
    branches:
      - 'master'
  pull_request: {}
jobs:
  build:
    name: Build, lint, and test (React ${{ matrix.react-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        react-version:
          - 19.0.0
          - latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.2
          run_install: false

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Override React version (${{ matrix.react-version }})
        run: |
          pnpm add react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} -D -w

      - name: Build
        run: pnpm run build

      - name: Check types
        run: pnpm run typecheck

      - name: Check lint
        run: pnpm run eslint

      - name: Jest run
        run: pnpm run dev && pnpm run test

      - name: Report Fiber size
        run: pnpm run analyze-fiber

      - name: Report Test Renderer size
        run: pnpm run analyze-test

      - name: Check formatting
        run: pnpm run format
